-- Rolls the PostgreSQL schema back from V133 to V126, undoing the analytics move to ClickHouse.
--
-- WHEN
--   Only to abandon the release that added V127 to V133 (analytics in ClickHouse). It restores the
--   schema the previous backend image expects; it does not restore data. Every row the dropped
--   tables held (user_events, platform_stats) was disposable seed or behavioural data and is
--   regenerated by a reseed, and the previous backend image needs one before its activity log and
--   statistics screens show anything.
--
-- WHO AND HOW
--   Run as the database owner, once, against the application database, with the new backend
--   STOPPED and the previous backend image not yet started:
--
--     psql -v ON_ERROR_STOP=1 -1 -f phase2_postgres_rollback.sql "$DATABASE_URL"
--
--   The previous image validates Flyway history at startup and refuses to start while V127 to V133
--   are recorded as applied but unknown to it; this script deletes those rows, so it has to run
--   first. Then start the previous image, then reseed.
--
-- WHAT IT DOES, IN ORDER
--   1. Recreates what V130, V131 and V132 dropped: stat_granularity, platform_stats and its series
--      index (V70, V71); event_type, user_events with its default partition, the current and next
--      two monthly partitions and its three indexes (V14, V15, V28, V69); post_interaction_scores
--      and user_similarity with their indexes (V14, V15). The previous backend image truncates all
--      of these on a seed reset, so they must exist.
--   2. Removes what V127, V128 and V133 added: the two admin_actions triggers, their functions and
--      the row_version column; the notifications foreign key; gorse_rebuild_runs.
--   3. Sets the V128 archive table aside as archived_notification_admin_action_orphans_before_rollback
--      instead of dropping it, so its rows survive and a later re-run of V128 can create its own.
--   4. Deletes the V127 to V133 rows from flyway_schema_history, so a later redeploy of the new
--      release applies them again from a schema equal to V126.
--
-- IDEMPOTENT
--   A second run changes nothing: every create is guarded, every drop is IF EXISTS, and the archive
--   step folds a second archive into the first.
--
-- INDEXES
--   The recreated tables are empty, so the indexes are built without CONCURRENTLY: there is no
--   write to block, and CONCURRENTLY cannot run inside the single transaction this script uses.

-- 1. Recreate the dropped objects -------------------------------------------------------------

DO $$
BEGIN
    IF to_regtype('stat_granularity') IS NULL THEN
        CREATE TYPE stat_granularity AS ENUM ('half_hour', 'day');
    END IF;
    IF to_regtype('event_type') IS NULL THEN
        CREATE TYPE event_type AS ENUM (
            'post_view', 'post_like', 'post_unlike',
            'post_save', 'post_unsave', 'post_share', 'post_comment',
            'story_view', 'story_reply',
            'profile_view', 'profile_follow', 'profile_unfollow',
            'search', 'hashtag_click',
            'comment_like', 'comment_reply',
            'message_send',
            'session_start', 'session_end', 'app_open'
        );
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS platform_stats (
    bucket_start TIMESTAMPTZ      NOT NULL,
    granularity  stat_granularity NOT NULL,
    metric_key   VARCHAR(64)      NOT NULL,
    dimension    VARCHAR(64)      NOT NULL DEFAULT '',
    value        BIGINT           NOT NULL,
    computed_at  TIMESTAMPTZ      NOT NULL DEFAULT NOW(),
    PRIMARY KEY (bucket_start, granularity, metric_key, dimension)
);

CREATE INDEX IF NOT EXISTS idx_platform_stats_series
    ON platform_stats (metric_key, granularity, bucket_start DESC);

CREATE TABLE IF NOT EXISTS user_events (
    id                  UUID            NOT NULL DEFAULT gen_random_uuid(),
    user_id             UUID            NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    session_id          UUID,
    event_type          event_type      NOT NULL,
    entity_type         VARCHAR(50),
    entity_id           UUID,
    metadata            JSONB,
    ip_address          INET,
    user_agent          TEXT,
    platform            VARCHAR(10)     CHECK (platform IN ('ios', 'android', 'web')),
    created_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id, created_at)
) PARTITION BY RANGE (created_at);

CREATE TABLE IF NOT EXISTS user_events_default PARTITION OF user_events DEFAULT;

-- The previous image's UserEventsPartitionJob keeps the window going once it is running; this
-- declares the same current month plus two ahead that V28 did, so the first events after the
-- rollback do not land in the default partition.
DO $$
DECLARE
    month_start DATE;
    partition_name TEXT;
BEGIN
    FOR i IN 0..2 LOOP
        month_start := date_trunc('month', CURRENT_DATE + (i * INTERVAL '1 month'))::date;
        partition_name := 'user_events_' || to_char(month_start, 'YYYY_MM');
        EXECUTE format(
            'CREATE TABLE IF NOT EXISTS %I PARTITION OF user_events '
                || 'FOR VALUES FROM (%L) TO (%L)',
            partition_name,
            month_start,
            month_start + INTERVAL '1 month'
        );
    END LOOP;
END $$;

CREATE INDEX IF NOT EXISTS idx_user_events_user   ON user_events (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_user_events_type   ON user_events (event_type, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_user_events_entity ON user_events (entity_type, entity_id, created_at DESC)
    WHERE entity_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS post_interaction_scores (
    post_id             UUID            PRIMARY KEY REFERENCES posts(id) ON DELETE CASCADE,
    view_score          DECIMAL(10,4)   NOT NULL DEFAULT 0,
    engagement_score    DECIMAL(10,4)   NOT NULL DEFAULT 0,
    recency_score       DECIMAL(10,4)   NOT NULL DEFAULT 0,
    total_score         DECIMAL(10,4)   NOT NULL DEFAULT 0,
    computed_at         TIMESTAMPTZ     NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_post_scores_total ON post_interaction_scores (total_score DESC);

CREATE TABLE IF NOT EXISTS user_similarity (
    user_id_a           UUID            NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    user_id_b           UUID            NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    similarity_score    DECIMAL(6,4)    NOT NULL CHECK (similarity_score BETWEEN 0 AND 1),
    computed_at         TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    PRIMARY KEY (user_id_a, user_id_b),
    CHECK (user_id_a < user_id_b)
);

CREATE INDEX IF NOT EXISTS idx_user_sim_score ON user_similarity (user_id_a, similarity_score DESC);

-- 2. Remove what V127, V128 and V133 added ----------------------------------------------------

DROP TRIGGER IF EXISTS trg_admin_actions_enqueue_replication ON admin_actions;
DROP TRIGGER IF EXISTS trg_admin_actions_bump_row_version ON admin_actions;
DROP FUNCTION IF EXISTS fn_admin_actions_enqueue_replication();
DROP FUNCTION IF EXISTS fn_admin_actions_bump_row_version();
ALTER TABLE admin_actions DROP COLUMN IF EXISTS row_version;

ALTER TABLE notifications DROP CONSTRAINT IF EXISTS fk_notifications_admin_action;

DROP TABLE IF EXISTS gorse_rebuild_runs;

-- 3. Set the V128 archive aside ---------------------------------------------------------------

DO $$
BEGIN
    IF to_regclass('archived_notification_admin_action_orphans') IS NOT NULL THEN
        IF to_regclass('archived_notification_admin_action_orphans_before_rollback') IS NULL THEN
            ALTER TABLE archived_notification_admin_action_orphans
                RENAME TO archived_notification_admin_action_orphans_before_rollback;
        ELSE
            INSERT INTO archived_notification_admin_action_orphans_before_rollback
            SELECT * FROM archived_notification_admin_action_orphans;
            DROP TABLE archived_notification_admin_action_orphans;
        END IF;
    END IF;
END $$;

-- 4. Forget V127 to V133 ----------------------------------------------------------------------

DELETE FROM flyway_schema_history
WHERE version IN ('127', '128', '129', '130', '131', '132', '133');
