package com.app.modules.recommendation.repository;

import java.time.OffsetDateTime;
import java.util.Collection;
import java.util.List;
import java.util.UUID;
import java.util.function.Consumer;

import com.app.modules.recommendation.enums.UserEventType;

/**
 * Reads and writes the behavioural event store, {@code luvax_analytics.user_events} in ClickHouse.
 *
 * <p>Every method goes through {@code ClickHouseOperations}, so each one can fail with {@link
 * com.app.common.analytics.ClickHouseUnavailableException} and each caller decides what an outage
 * means for it: the recorder drops the row, a consumer requeues the message, the administrative
 * reads answer a typed 503, and the recommendation read-set degrades to Gorse's results alone.
 *
 * <p>The table is a {@code ReplacingMergeTree} keyed on the event id, so a redelivered event lands
 * on the same key and a merge folds it away; a read that must be exact says {@code FINAL}, and one
 * that only builds a set does not.
 */
public interface UserEventAnalyticsRepository {

    /**
     * One account's decayed contribution towards a post or a hashtag, summed over the window.
     *
     * @param userId the account
     * @param targetKind {@code post} when {@code targetId} is a post, {@code hashtag} when it is a
     *     hashtag the account clicked
     * @param targetId the post or hashtag
     * @param contribution weighted, time-decayed sum of the account's events on the target
     * @param eventCount how many events contributed
     */
    record AffinitySignal(
            UUID userId, String targetKind, UUID targetId, double contribution, long eventCount) {}

    /**
     * The feedback a user has accumulated on one item, as the live pipeline sent it to Gorse.
     *
     * @param feedbackType the Gorse feedback type
     * @param userId the account
     * @param itemId the item, a post id
     * @param value sum of the values sent for this (type, user, item)
     * @param latest time of the newest event contributing to it
     */
    record FeedbackTotal(
            String feedbackType, UUID userId, UUID itemId, double value, OffsetDateTime latest) {}

    /**
     * Inserts one event without waiting for it to be written, for the recorder.
     *
     * <p>The insert is acknowledged as soon as it is buffered, so a data error or a crash inside
     * the flush window loses the row silently; the recorder's contract is to drop rather than slow
     * or fail a request, and ClickHouse's failed-insert counter is what makes those losses visible.
     * The event id is generated by ClickHouse.
     *
     * @param userId account the event is attributed to
     * @param eventType what happened
     * @param entityType kind of thing acted on, null when none
     * @param entityId thing acted on, null when none
     * @param metadata JSON text, or empty
     * @param createdAt when the request happened, taken on the request thread
     */
    void recordDetached(
            UUID userId,
            UserEventType eventType,
            String entityType,
            UUID entityId,
            String metadata,
            OffsetDateTime createdAt);

    /**
     * Inserts one engagement event and returns only once the part is written, for the consumer that
     * feeds Gorse.
     *
     * <p>The event id is the domain event's id and the time is its {@code occurredAt}, so a
     * redelivery writes an identical row that the engine folds away. The Gorse feedback type and
     * value the event is about to be sent with are stored beside it, so a rebuild reproduces
     * exactly what the live pipeline accumulated.
     *
     * @param eventId domain event id, reused as the row id
     * @param userId acting account
     * @param eventType what happened
     * @param entityType kind of thing acted on, for example {@code post}
     * @param entityId thing acted on
     * @param occurredAt when the domain event happened
     * @param feedbackType Gorse feedback type sent for this event
     * @param feedbackValue Gorse feedback value sent for this event
     */
    void insertEngagement(
            UUID eventId,
            UUID userId,
            UserEventType eventType,
            String entityType,
            UUID entityId,
            OffsetDateTime occurredAt,
            String feedbackType,
            double feedbackValue);

    /**
     * Inserts one imported event and returns only once the part is written.
     *
     * <p>Imported rows carry no Gorse feedback, so a rebuild never replays them into the
     * recommender.
     *
     * @param eventId identifier the import assigned to the event
     * @param userId account the event is attributed to
     * @param eventType what happened
     * @param entityType kind of thing acted on, null when none
     * @param entityId thing acted on, null when none
     * @param metadata JSON text, or empty
     * @param createdAt when the event happened
     */
    void insertImported(
            UUID eventId,
            UUID userId,
            UserEventType eventType,
            String entityType,
            UUID entityId,
            String metadata,
            OffsetDateTime createdAt);

    /**
     * Reads one keyset page of events inside a mandatory window, newest first.
     *
     * <p>Ties on the timestamp are ordered by the identifier as text, the same order the audit log
     * uses, so every cursor in the application means the same thing. The read is {@code FINAL}, so
     * an event whose duplicate has not merged yet is shown once.
     *
     * @param userId restrict to one account, or null for every account in the window
     * @param from inclusive lower bound
     * @param to exclusive upper bound
     * @param eventType restrict to one type, or null for all
     * @param cursorCreatedAt keyset position timestamp, null for the first page
     * @param cursorId keyset position tiebreaker, null for the first page
     * @param limit maximum rows, normally the page size plus one
     * @return events newest first
     */
    List<UserEventRow> findPage(
            UUID userId,
            OffsetDateTime from,
            OffsetDateTime to,
            UserEventType eventType,
            OffsetDateTime cursorCreatedAt,
            UUID cursorId,
            int limit);

    /**
     * Reads up to {@code limit} of an account's most recent {@code entity_id} values for one type,
     * newest first.
     *
     * <p>Built for the recommendation read-set, so it is not {@code FINAL}: the caller collects
     * into a set and a duplicate changes nothing. The result can repeat an id, since a post viewed
     * twice is two rows.
     *
     * @param userId account whose events are read
     * @param eventType restrict to this type
     * @param from inclusive lower bound
     * @param to exclusive upper bound
     * @param limit maximum rows
     * @return entity ids newest first, possibly with repeats
     */
    List<UUID> findRecentEntityIds(
            UUID userId,
            UserEventType eventType,
            OffsetDateTime from,
            OffsetDateTime to,
            int limit);

    /**
     * Streams every account's decayed contribution towards each post or hashtag it touched in the
     * window, in batches.
     *
     * <p>Each batch is handed to {@code sink} as it arrives, so the whole result set is never held
     * in memory. A failure raised by the sink is rethrown as it is, never mistaken for a ClickHouse
     * failure. The read is {@code FINAL}, so the sums are exact.
     *
     * @param windowStart inclusive lower bound
     * @param windowEnd exclusive upper bound, and the instant decay is measured back from
     * @param halfLifeSeconds age at which a contribution is worth half its weight
     * @param batchSize rows per batch
     * @param sink receives each batch
     */
    void streamAffinitySignals(
            OffsetDateTime windowStart,
            OffsetDateTime windowEnd,
            long halfLifeSeconds,
            int batchSize,
            Consumer<List<AffinitySignal>> sink);

    /**
     * Sums the Gorse feedback each of the given accounts has accumulated per item.
     *
     * <p>Only events that were sent to Gorse carry a feedback type, so imported and recorder rows
     * are ignored. The read is {@code FINAL} and batched by account, which keeps its memory inside
     * the reader profile.
     *
     * @param userIds accounts to read, a bounded batch
     * @return one total per (feedback type, account, item)
     */
    List<FeedbackTotal> findFeedbackTotals(Collection<UUID> userIds);
}
