-- Platform statistics now live in ClickHouse (luvax_analytics.platform_stats), written through the
-- outbox; daily figures are computed at query time, so the roll-up's daily rows have no successor.
-- Rows are dropped without an archive: the Phase 2 decision is to drop this table, and every row
-- is seeded and regenerated by the reseed that follows this release.
DROP TABLE platform_stats;
DROP TYPE stat_granularity;
