-- Behavioural events now live in ClickHouse (luvax_analytics.user_events), partitioned monthly
-- with a 12-month TTL. Dropping the partitioned parent drops every monthly partition and
-- user_events_default with it. Rows are dropped without an archive: the Phase 2 decision is to move
-- this table, and every row is seeded and regenerated by the reseed that follows this release.
DROP TABLE user_events;
DROP TYPE event_type;
