package com.app.modules.admin.messaging;

import java.nio.charset.StandardCharsets;
import java.time.Instant;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;

import com.app.common.messaging.exception.PermanentMessageException;

/**
 * The payload contract of {@link AdminEventTypes#PLATFORM_STATS_COLLECTED_V1}: one collected
 * statistics bucket, every metric row of it in one event.
 *
 * <p>The producer (the collection service, and the development seed) and the consumer both go
 * through this class, so the two ends of the queue cannot drift apart on a key name.
 *
 * <p>A bucket has no PostgreSQL row to borrow an identifier from, so its aggregate identifier is
 * derived from the bucket start. This is the documented reason {@code GLOBAL_RULES.md} section 5
 * asks for when an identifier is not generated by the database: the same bucket must always map to
 * the same aggregate so a re-collection is recognisably a restatement of the earlier one.
 */
public final class PlatformStatsCollectedEvent {

    public static final String AGGREGATE_TYPE = "platform_stats_bucket";

    private PlatformStatsCollectedEvent() {}

    /** One metric and dimension of a bucket. */
    public record Row(String metricKey, String dimension, long value) {}

    /** The bucket an event carries, as the consumer reads it. */
    public record Bucket(Instant bucketStart, Instant computedAt, List<Row> rows) {}

    /**
     * The aggregate identifier of a bucket: a name-based UUID over its start instant, so the same
     * bucket always yields the same identifier whatever offset the caller held it in.
     */
    public static UUID aggregateId(Instant bucketStart) {
        return UUID.nameUUIDFromBytes(
                ("platform_stats:" + bucketStart).getBytes(StandardCharsets.UTF_8));
    }

    /** Builds the event's {@code data} map. */
    public static Map<String, Object> payload(
            Instant bucketStart, long bucketSeconds, Instant computedAt, List<Row> rows) {
        List<Map<String, Object>> rowMaps = new ArrayList<>(rows.size());
        for (Row row : rows) {
            Map<String, Object> rowMap = new LinkedHashMap<>();
            rowMap.put("metricKey", row.metricKey());
            rowMap.put("dimension", row.dimension());
            rowMap.put("value", row.value());
            rowMaps.add(rowMap);
        }
        Map<String, Object> data = new LinkedHashMap<>();
        data.put("bucketStart", bucketStart.toString());
        data.put("bucketSeconds", bucketSeconds);
        data.put("computedAt", computedAt.toString());
        data.put("rows", rowMaps);
        return data;
    }

    /**
     * Reads a delivered event's {@code data} map.
     *
     * @throws PermanentMessageException when the payload is missing a field or holds a value of the
     *     wrong shape, because redelivering it cannot make it valid
     */
    public static Bucket parse(Map<String, Object> data) {
        if (data == null) {
            throw new PermanentMessageException("Platform statistics event has no data");
        }
        try {
            Instant bucketStart = Instant.parse(text(data, "bucketStart"));
            Instant computedAt = Instant.parse(text(data, "computedAt"));
            Object rawRows = data.get("rows");
            if (!(rawRows instanceof List<?> rowList)) {
                throw new PermanentMessageException("Platform statistics event has no rows");
            }
            List<Row> rows = new ArrayList<>(rowList.size());
            for (Object rawRow : rowList) {
                if (!(rawRow instanceof Map<?, ?> rowMap)) {
                    throw new PermanentMessageException("Platform statistics row is not an object");
                }
                Object value = rowMap.get("value");
                if (!(value instanceof Number number)) {
                    throw new PermanentMessageException("Platform statistics row has no value");
                }
                rows.add(
                        new Row(
                                text(rowMap, "metricKey"),
                                rowMap.get("dimension") == null
                                        ? ""
                                        : rowMap.get("dimension").toString(),
                                number.longValue()));
            }
            return new Bucket(bucketStart, computedAt, rows);
        } catch (java.time.format.DateTimeParseException ex) {
            throw new PermanentMessageException(
                    "Platform statistics event has a bad timestamp", ex);
        }
    }

    private static String text(Map<?, ?> map, String key) {
        Object value = map.get(key);
        if (value == null || value.toString().isBlank()) {
            throw new PermanentMessageException("Platform statistics event has no " + key);
        }
        return value.toString();
    }
}
